#!/usr/bin/env sh

# initialize darwin flag to false
darwin=false

# check for --darwin flag
while [ "$1" != "" ]; do
  case $1 in
  --darwin)
    darwin=true
    ;;
  *)
    echo "Invalid option: $1"
    exit 1
    ;;
  esac
  shift
done

# add custom behavior based on darwin flag
if [ "$darwin" = true ]; then
  PVIM=$(dirname $(readlink -f -- "$0"))
  echo "Updating for Darwin..."
  $PVIM/pvim-update-darwin
else
  PVIM=$(dirname $(readlink -e -- "$0"))
  echo "Updating for Linux..."
  $PVIM/pvim-update-linux
fi
