-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "catppuccin-mocha"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@class", { fg = "#71b9fc" })
hi(0, "@constant", { fg = "#f9b36f" })
hi(0, "@constant.builtin", { fg = "#f9b36f" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#47ceef" })
hi(0, "@constructor.lua", { fg = "#fccac2" })
hi(0, "@constructor.tsx", { fg = "#bdb9fc" })
hi(0, "@constructor.typescript", { fg = "#bdb9fc" })
hi(0, "@decorator", { fg = "#fccac2" })
hi(0, "@enum", { fg = "#7de8c9" })
hi(0, "@enumMember", { fg = "#fccac2" })
hi(0, "@error", { link = "Error" })
hi(0, "@event", { fg = "#fccac2" })
hi(0, "@exception", { fg = "#dc9cf4" })
hi(0, "@field", { fg = "#bdb9fc" })
hi(0, "@field.yaml", { fg = "#71b9fc" })
hi(0, "@float", { link = "Number" })
hi(0, "@function.builtin", { fg = "#f9b36f" })
hi(0, "@function.call", { link = "@function" })
hi(0, "@function.macro", { fg = "#7de8c9" })
hi(0, "@interface", { fg = "#fccac2" })
hi(0, "@keyword.export", { bold = true, fg = "#65e2ea" })
hi(0, "@keyword.function", { fg = "#dc9cf4" })
hi(0, "@keyword.operator", { fg = "#dc9cf4" })
hi(0, "@keyword.return", { fg = "#dc9cf4" })
hi(0, "@label.json", { fg = "#71b9fc" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "Function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "Constant" })
hi(0, "@lsp.type.function", { link = "Function" })
hi(0, "@lsp.type.interface", { link = "@interface" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.method", { link = "Function" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.struct", { link = "Structure" })
hi(0, "@lsp.type.type", { link = "Type" })
hi(0, "@lsp.type.typeParameter", { link = "Typedef" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@method", { fg = "#f9b36f" })
hi(0, "@method.call", { link = "@method" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@modifier", { fg = "#fccac2" })
hi(0, "@namespace", { fg = "#bdb9fc", italic = true })
hi(0, "@number.css", { fg = "#f9b36f" })
hi(0, "@parameter", { fg = "#fc9799", italic = true })
hi(0, "@property", { fg = "#bdb9fc" })
hi(0, "@property.class.css", { fg = "#fbe29f" })
hi(0, "@property.cpp", { fg = "#fbdfd5" })
hi(0, "@property.css", { fg = "#bdb9fc" })
hi(0, "@property.id.css", { fg = "#71b9fc" })
hi(0, "@property.toml", { fg = "#71b9fc" })
hi(0, "@punctuation.bracket", { fg = "#9494c6" })
hi(0, "@punctuation.delimiter", { fg = "#9494c6" })
hi(0, "@punctuation.special", { fg = "#65e2ea" })
hi(0, "@regexp", { fg = "#ffb9e2" })
hi(0, "@string.escape", { fg = "#ffb9e2" })
hi(0, "@string.plain.css", { fg = "#f9b36f" })
hi(0, "@string.regex", { fg = "#f9b36f" })
hi(0, "@string.special", { fg = "#71b9fc" })
hi(0, "@struct", { fg = "#71b9fc" })
hi(0, "@symbol", { fg = "#fccac2" })
hi(0, "@symbol.ruby", { fg = "#fccac2" })
hi(0, "@tag", { fg = "#dc9cf4" })
hi(0, "@tag.attribute", { fg = "#7de8c9", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#dc9cf4", italic = true })
hi(0, "@tag.delimiter", { fg = "#65e2ea" })
hi(0, "@text", { fg = "#d1d4fc" })
hi(0, "@text.danger", { bg = "#b2a2f1", fg = "#221939" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = "#fc9799", italic = true })
hi(0, "@text.environment", { fg = "#ffb9e2" })
hi(0, "@text.environment.name", { fg = "#71b9fc" })
hi(0, "@text.literal", { fg = "#7de8c9" })
hi(0, "@text.math", { fg = "#71b9fc" })
hi(0, "@text.note", { bg = "#9ab0f2", fg = "#221939" })
hi(0, "@text.reference", { bold = true, fg = "#bdb9fc" })
hi(0, "@text.strike", { fg = "#d1d4fc", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#fc9799" })
hi(0, "@text.title", { bold = true, fg = "#71b9fc" })
hi(0, "@text.todo", { bg = "#ffd5d7", fg = "#221939" })
hi(0, "@text.todo.checked", { fg = "#a5e76e" })
hi(0, "@text.todo.unchecked", { fg = "#817eb4" })
hi(0, "@text.underline", { link = "Underline" })
hi(0, "@text.uri", { fg = "#fbdfd5", italic = true, underline = true })
hi(0, "@text.warning", { bg = "#ffd5d7", fg = "#221939" })
hi(0, "@type.builtin", { fg = "#fbe29f" })
hi(0, "@type.css", { fg = "#bdb9fc" })
hi(0, "@type.definition", { link = "@type" })
hi(0, "@type.qualifier", { link = "@type" })
hi(0, "@type.qualifier.php", { link = "Keyword" })
hi(0, "@type.tag.css", { fg = "#dc9cf4" })
hi(0, "@typeParameter", { fg = "#fbe29f" })
hi(0, "@variable", { fg = "#d1d4fc" })
hi(0, "@variable.builtin", { fg = "#ff7e93" })
hi(0, "AlphaButtons", { fg = "#bdb9fc" })
hi(0, "AlphaFooter", { fg = "#fbe29f", italic = true })
hi(0, "AlphaHeader", { fg = "#71b9fc" })
hi(0, "AlphaHeaderLabel", { fg = "#f9b36f" })
hi(0, "AlphaShortcut", { fg = "#a5e76e" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#f9b36f" })
hi(0, "BufferLineBackground", { bg = "#171a1f", fg = "#6e69a2" })
hi(0, "BufferLineBuffer", { bg = "#15181d", fg = "#6e69a2" })
hi(0, "BufferLineBufferSelected", { bg = "#1d2027", bold = true, fg = "#d1d4fc", italic = true, sp = "#45475a", underline = true })
hi(0, "BufferLineBufferVisible", { bg = "#171a1f", fg = "#494071" })
hi(0, "BufferLineCloseButton", { bg = "#171a1f", fg = "#494071" })
hi(0, "BufferLineCloseButtonSelected", { bg = "#1d2027", fg = "#ff7e93", sp = "#45475a", underline = true })
hi(0, "BufferLineCloseButtonVisible", { bg = "#171a1f", fg = "#494071" })
hi(0, "BufferLineDevIconDefault", { bg = "#171a1f", fg = "#5c848b" })
hi(0, "BufferLineDevIconDefaultInactive", { bg = "#171a1f", fg = "#5c848b" })
hi(0, "BufferLineDevIconDefaultSelected", { bg = "#1d2027", fg = "#5c848b", sp = "#45475a", underline = true })
hi(0, "BufferLineDiagnostic", { bg = "#171a1f", fg = "#a8a9d9" })
hi(0, "BufferLineDiagnosticSelected", { bg = "#1d2027", bold = true, fg = "#a8a9d9", italic = true, sp = "#45475a", underline = true })
hi(0, "BufferLineDiagnosticVisible", { bg = "#171a1f", fg = "#a8a9d9" })
hi(0, "BufferLineDuplicate", { bg = "#171a1f", bold = true, fg = "#494071", italic = true })
hi(0, "BufferLineDuplicateSelected", { bg = "#1d2027", bold = true, fg = "#d1d4fc", italic = true, sp = "#45475a", underline = true })
hi(0, "BufferLineDuplicateVisible", { bg = "#171a1f", bold = true, fg = "#494071", italic = true })
hi(0, "BufferLineError", { bg = "#171a1f", fg = "#ff7e93", sp = "#f38ba8" })
hi(0, "BufferLineErrorDiagnostic", { bg = "#171a1f", fg = "#ff7e93", sp = "#b6687e" })
hi(0, "BufferLineErrorDiagnosticSelected", { bg = "#1d2027", fg = "#ff7e93", sp = "#45475a", underline = true })
hi(0, "BufferLineErrorDiagnosticVisible", { bg = "#171a1f", fg = "#ff7e93" })
hi(0, "BufferLineErrorSelected", { bg = "#1d2027", bold = true, fg = "#ff7e93", italic = true, sp = "#45475a", underline = true })
hi(0, "BufferLineErrorVisible", { bg = "#171a1f", fg = "#ff7e93" })
hi(0, "BufferLineFill", { bg = "#111216", fg = "#6e69a2" })
hi(0, "BufferLineGroupLabel", { bg = "#6f7177", fg = "#120d21" })
hi(0, "BufferLineGroupSeparator", { bg = "#101115", fg = "#6e69a2" })
hi(0, "BufferLineHint", { bg = "#171a1f", fg = "#7de8c9", sp = "#94e2d5" })
hi(0, "BufferLineHintDiagnostic", { bg = "#171a1f", fg = "#7de8c9", sp = "#6fa99f" })
hi(0, "BufferLineHintDiagnosticSelected", { bg = "#1d2027", fg = "#7de8c9", sp = "#45475a", underline = true })
hi(0, "BufferLineHintDiagnosticVisible", { bg = "#171a1f", fg = "#7de8c9" })
hi(0, "BufferLineHintSelected", { bg = "#1d2027", bold = true, fg = "#7de8c9", italic = true, sp = "#45475a", underline = true })
hi(0, "BufferLineHintVisible", { bg = "#171a1f", fg = "#7de8c9" })
hi(0, "BufferLineIndicatorSelected", { bg = "#1d2027", bold = true, fg = "#f9b36f", italic = true, sp = "#45475a", underline = true })
hi(0, "BufferLineIndicatorVisible", { bg = "#1a1d24", fg = "#1f1634" })
hi(0, "BufferLineInfo", { bg = "#171a1f", fg = "#65e2ea", sp = "#89dceb" })
hi(0, "BufferLineInfoDiagnostic", { bg = "#171a1f", fg = "#65e2ea", sp = "#66a5b0" })
hi(0, "BufferLineInfoDiagnosticSelected", { bg = "#1d2027", fg = "#65e2ea", sp = "#45475a", underline = true })
hi(0, "BufferLineInfoDiagnosticVisible", { bg = "#171a1f", fg = "#65e2ea" })
hi(0, "BufferLineInfoSelected", { bg = "#1d2027", bold = true, fg = "#65e2ea", italic = true, sp = "#45475a", underline = true })
hi(0, "BufferLineInfoVisible", { bg = "#171a1f", fg = "#65e2ea" })
hi(0, "BufferLineModified", { bg = "#171a1f", fg = "#f9b36f" })
hi(0, "BufferLineModifiedSelected", { bg = "#1d2027", fg = "#f9b36f", sp = "#45475a", underline = true })
hi(0, "BufferLineModifiedVisible", { bg = "#1a1d24", fg = "#a5e76e" })
hi(0, "BufferLineNumbers", { bg = "#171a1f", fg = "#a8a9d9" })
hi(0, "BufferLineNumbersSelected", { bg = "#1d2027", bold = true, fg = "#a8a9d9", italic = true, sp = "#45475a", underline = true })
hi(0, "BufferLineNumbersVisible", { bg = "#171a1f", fg = "#a8a9d9" })
hi(0, "BufferLineOffsetSeparator", { bg = "#1d2027", fg = "#130e23" })
hi(0, "BufferLinePick", { bg = "#15181d", bold = true, fg = "#ff7e93", italic = true })
hi(0, "BufferLinePickSelected", { bg = "#1d2027", bold = true, fg = "#ff7e93", italic = true, sp = "#45475a", underline = true })
hi(0, "BufferLinePickVisible", { bg = "#1a1d24", bold = true, fg = "#ff7e93", italic = true })
hi(0, "BufferLineSeparator", { bg = "#171a1f", fg = "#130e23" })
hi(0, "BufferLineSeparatorSelected", { bg = "#1d2027", fg = "#130e23", sp = "#45475a", underline = true })
hi(0, "BufferLineSeparatorVisible", { bg = "#171a1f", fg = "#130e23" })
hi(0, "BufferLineTab", { bg = "#171a1f", fg = "#494071" })
hi(0, "BufferLineTabClose", { bg = "#171a1f", fg = "#ff7e93" })
hi(0, "BufferLineTabSelected", { bg = "#1d2027", fg = "#65e2ea", sp = "#45475a", underline = true })
hi(0, "BufferLineTabSeparator", { bg = "#171a1f", fg = "#130e23" })
hi(0, "BufferLineTabSeparatorSelected", { bg = "#1d2027", fg = "#130e23", sp = "#45475a", underline = true })
hi(0, "BufferLineWarning", { bg = "#171a1f", fg = "#fbe29f", sp = "#f9e2af" })
hi(0, "BufferLineWarningDiagnostic", { bg = "#171a1f", fg = "#fbe29f", sp = "#baa983" })
hi(0, "BufferLineWarningDiagnosticSelected", { bg = "#1d2027", fg = "#fbe29f", sp = "#45475a", underline = true })
hi(0, "BufferLineWarningDiagnosticVisible", { bg = "#171a1f", fg = "#fbe29f" })
hi(0, "BufferLineWarningSelected", { bg = "#1d2027", bold = true, fg = "#fbe29f", italic = true, sp = "#45475a", underline = true })
hi(0, "BufferLineWarningVisible", { bg = "#171a1f", fg = "#fbe29f" })
hi(0, "Character", { fg = "#7de8c9" })
hi(0, "CmpItemAbbr", { fg = "#9494c6" })
hi(0, "CmpItemAbbrDefault", { fg = "#9494c6" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#6e69a2", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#6e69a2" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#dc9cf4" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#9494c6" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#dc9cf4" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#9494c6" })
hi(0, "CmpItemKind", { fg = "#71b9fc" })
hi(0, "CmpItemKindClass", { fg = "#fbe29f" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#ff7e93" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#f9b36f" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#71b9fc" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#7de8c9" })
hi(0, "CmpItemKindDefault", { fg = "#ffb9e2" })
hi(0, "CmpItemKindEnum", { fg = "#a5e76e" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#ff7e93" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#71b9fc" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#a5e76e" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#71b9fc" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#71b9fc" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#71b9fc" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#fbe29f" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#ff7e93" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#71b9fc" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#71b9fc" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#71b9fc" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#a5e76e" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#ff7e93" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#dc9cf4" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#71b9fc" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#7de8c9" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#71b9fc" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#a5e76e" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#f9b36f" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#fccac2" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#d1d4fc" })
hi(0, "CmpItemMenuDefault", { fg = "#9494c6" })
hi(0, "ColorColumn", { bg = "#31343a" })
hi(0, "Comment", { fg = "#6e69a2", italic = true })
hi(0, "Conceal", { fg = "#817eb4" })
hi(0, "Conditional", { fg = "#dc9cf4", italic = true })
hi(0, "Constant", { fg = "#f9b36f" })
hi(0, "CurSearch", { bg = "#b2a2f1", fg = "#1b142e" })
hi(0, "Cursor", { bg = "#ced6ef", fg = "#221939" })
hi(0, "CursorColumn", { bg = "#171a1f" })
hi(0, "CursorIM", { bg = "#ced6ef", fg = "#221939" })
hi(0, "CursorLine", { bg = "#2a2c33" })
hi(0, "CursorLineNr", { fg = "#71b9fc" })
hi(0, "DashboardCenter", { fg = "#a5e76e" })
hi(0, "DashboardFiles", { fg = "#bdb9fc" })
hi(0, "DashboardFooter", { fg = "#fbe29f", italic = true })
hi(0, "DashboardHeader", { fg = "#71b9fc" })
hi(0, "DashboardMruTitle", { fg = "#65e2ea" })
hi(0, "DashboardProjectTitle", { fg = "#65e2ea" })
hi(0, "DashboardShortCut", { fg = "#ffb9e2" })
hi(0, "DiagnosticError", { fg = "#ff7e93", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#ff7e93" })
hi(0, "DiagnosticFloatingHint", { fg = "#7de8c9" })
hi(0, "DiagnosticFloatingInfo", { fg = "#65e2ea" })
hi(0, "DiagnosticFloatingWarn", { fg = "#fbe29f" })
hi(0, "DiagnosticHint", { fg = "#7de8c9", italic = true })
hi(0, "DiagnosticInfo", { fg = "#65e2ea", italic = true })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#96f04d" })
hi(0, "DiagnosticSignError", { fg = "#ff7e93" })
hi(0, "DiagnosticSignHint", { fg = "#7de8c9" })
hi(0, "DiagnosticSignInfo", { fg = "#65e2ea" })
hi(0, "DiagnosticSignWarn", { fg = "#fbe29f" })
hi(0, "DiagnosticUnderlineError", { sp = "#f38ba8", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#94e2d5", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#89dceb", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#f9e2af", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#292c37", fg = "#ff7e93", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#2e3137", fg = "#7de8c9", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#2d3037", fg = "#65e2ea", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#323232", fg = "#fbe29f", italic = true })
hi(0, "DiagnosticWarn", { fg = "#fbe29f", italic = true })
hi(0, "DiffAdd", { bg = "#3d3f43" })
hi(0, "DiffChange", { bg = "#272a33" })
hi(0, "DiffDelete", { bg = "#343946" })
hi(0, "DiffText", { bg = "#464c5c" })
hi(0, "Directory", { fg = "#71b9fc" })
hi(0, "EndOfBuffer", { fg = "#221939" })
hi(0, "Error", { fg = "#ff7e93" })
hi(0, "ErrorMsg", { bold = true, fg = "#ff7e93", italic = true })
hi(0, "FidgetTask", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "FidgetTitle", { fg = "#71b9fc" })
hi(0, "Float", { fg = "#f9b36f" })
hi(0, "FloatBorder", { fg = "#71b9fc" })
hi(0, "FocusedSymbol", { fg = "#fbe29f" })
hi(0, "FoldColumn", { fg = "#6e69a2" })
hi(0, "Folded", { bg = "#47484d", fg = "#71b9fc" })
hi(0, "Function", { fg = "#71b9fc" })
hi(0, "GitSignsAdd", { fg = "#a5e76e" })
hi(0, "GitSignsAddPreview", { link = "DiffAdd" })
hi(0, "GitSignsChange", { fg = "#fbe29f" })
hi(0, "GitSignsDelete", { fg = "#ff7e93" })
hi(0, "GitSignsDeletePreview", { link = "DiffDelete" })
hi(0, "GlyphPalette1", { fg = "#ff7e93" })
hi(0, "GlyphPalette2", { fg = "#7de8c9" })
hi(0, "GlyphPalette3", { fg = "#fbe29f" })
hi(0, "GlyphPalette4", { fg = "#71b9fc" })
hi(0, "GlyphPalette6", { fg = "#7de8c9" })
hi(0, "GlyphPalette7", { fg = "#d1d4fc" })
hi(0, "GlyphPalette9", { fg = "#ff7e93" })
hi(0, "Identifier", { fg = "#fccac2" })
hi(0, "IlluminatedWordRead", { bg = "#3a3c42" })
hi(0, "IlluminatedWordText", { bg = "#3a3c42" })
hi(0, "IlluminatedWordWrite", { bg = "#3a3c42" })
hi(0, "IncSearch", { bg = "#abbae5", fg = "#1b142e" })
hi(0, "Include", { fg = "#dc9cf4" })
hi(0, "IndentBlanklineChar", { fg = "#352c55" })
hi(0, "IndentBlanklineContextChar", { fg = "#d1d4fc" })
hi(0, "IndentBlanklineContextStart", { sp = "#cdd6f4", underline = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#dc9cf4" })
hi(0, "Label", { fg = "#47ceef" })
hi(0, "LeapLabelPrimary", { bg = "#a0ebfc", fg = "#221939", nocombine = true })
hi(0, "LeapLabelSecondary", { bg = "#bbccfb", fg = "#221939", nocombine = true })
hi(0, "LeapMatch", { fg = "#b8f28b", nocombine = true, underline = true })
hi(0, "LineNr", { fg = "#494071" })
hi(0, "LspCodeLens", { fg = "#6e69a2" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#ff7e93" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#7de8c9" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#65e2ea" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#fbe29f" })
hi(0, "LspDiagnosticsError", { fg = "#ff7e93" })
hi(0, "LspDiagnosticsHint", { fg = "#7de8c9" })
hi(0, "LspDiagnosticsInformation", { fg = "#65e2ea" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#f38ba8", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#94e2d5", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#89dceb", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#f9e2af", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#ff7e93", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#7de8c9", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#65e2ea", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#fbe29f", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#fbe29f" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInfoFiletype", { fg = "#fbe29f" })
hi(0, "LspInfoList", { fg = "#71b9fc" })
hi(0, "LspInfoTip", { fg = "#6e69a2", italic = true })
hi(0, "LspInfoTitle", { bold = true, fg = "#71b9fc" })
hi(0, "LspLens", { fg = "#6e69a2", italic = true })
hi(0, "LspReferenceRead", { bg = "#47484d" })
hi(0, "LspReferenceText", { bg = "#47484d" })
hi(0, "LspReferenceWrite", { bg = "#47484d" })
hi(0, "LspSignatureActiveParameter", { fg = "#f9b36f" })
hi(0, "Macro", { fg = "#dc9cf4" })
hi(0, "MasonError", { fg = "#ff7e93" })
hi(0, "MasonHeader", { bg = "#afc1f8", bold = true, fg = "#221939" })
hi(0, "MasonHeaderSecondary", { bg = "#9ab0f2", bold = true, fg = "#221939" })
hi(0, "MasonHeading", { bold = true, fg = "#bdb9fc" })
hi(0, "MasonHighlight", { fg = "#a5e76e" })
hi(0, "MasonHighlightBlock", { bg = "#90deef", fg = "#221939" })
hi(0, "MasonHighlightBlockBold", { bg = "#9ab0f2", bold = true, fg = "#221939" })
hi(0, "MasonHighlightBlockBoldSecondary", { bg = "#afc1f8", bold = true, fg = "#221939" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#9ab0f2", fg = "#221939" })
hi(0, "MasonHighlightSecondary", { fg = "#dc9cf4" })
hi(0, "MasonMuted", { fg = "#6e69a2" })
hi(0, "MasonMutedBlock", { bg = "#6f7177", fg = "#221939" })
hi(0, "MasonMutedBlockBold", { bg = "#ffd5d7", bold = true, fg = "#221939" })
hi(0, "MatchParen", { bg = "#47484d", bold = true, fg = "#f9b36f" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#d1d4fc" })
hi(0, "MiniJump", { bg = "#c4d3ff", fg = "#9494c6" })
hi(0, "MiniJump2dSpot", { bg = "#1d2027", bold = true, fg = "#f9b36f", underline = true })
hi(0, "MiniStarterFooter", { fg = "#fbe29f", italic = true })
hi(0, "MiniStarterHeader", { fg = "#71b9fc" })
hi(0, "MiniStarterInactive", { fg = "#5b538e", italic = true })
hi(0, "MiniStarterItem", { fg = "#d1d4fc" })
hi(0, "MiniStarterItemBullet", { fg = "#71b9fc" })
hi(0, "MiniStarterItemPrefix", { fg = "#ffb9e2" })
hi(0, "MiniStarterQuery", { fg = "#a5e76e" })
hi(0, "MiniStarterSection", { fg = "#fccac2" })
hi(0, "MiniStatuslineDevinfo", { bg = "#47484d", fg = "#bcbeeb" })
hi(0, "MiniStatuslineFileinfo", { bg = "#47484d", fg = "#bcbeeb" })
hi(0, "MiniStatuslineFilename", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "MiniStatuslineInactive", { bg = "#171a1f", fg = "#71b9fc" })
hi(0, "MiniStatuslineModeCommand", { bg = "#efafd4", bold = true, fg = "#221939" })
hi(0, "MiniStatuslineModeInsert", { bg = "#90deef", bold = true, fg = "#221939" })
hi(0, "MiniStatuslineModeNormal", { bg = "#9ab0f2", bold = true, fg = "#1b142e" })
hi(0, "MiniStatuslineModeOther", { bg = "#b3d4fa", bold = true, fg = "#221939" })
hi(0, "MiniStatuslineModeReplace", { bg = "#b2a2f1", bold = true, fg = "#221939" })
hi(0, "MiniStatuslineModeVisual", { bg = "#a0b7fd", bold = true, fg = "#221939" })
hi(0, "MiniSurround", { bg = "#c4d3ff", fg = "#494071" })
hi(0, "MiniTablineCurrent", { bg = "#1d2027", bold = true, fg = "#d1d4fc", italic = true, sp = "#f38ba8", underline = true })
hi(0, "MiniTablineFill", { bg = "#1d2027" })
hi(0, "MiniTablineHidden", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "MiniTablineModifiedCurrent", { bold = true, fg = "#ff7e93", italic = true })
hi(0, "MiniTablineModifiedHidden", { fg = "#ff7e93" })
hi(0, "MiniTablineModifiedVisible", { fg = "#ff7e93" })
hi(0, "MiniTablineTabpagesection", { bg = "#1d2027", fg = "#494071" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#ff7e93" })
hi(0, "MiniTestPass", { bold = true, fg = "#a5e76e" })
hi(0, "MiniTrailspace", { bg = "#b2a2f1" })
hi(0, "ModeMsg", { bold = true, fg = "#d1d4fc" })
hi(0, "MoreMsg", { fg = "#71b9fc" })
hi(0, "MsgSeparator", {})
hi(0, "NeoTreeDimText", { fg = "#817eb4" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#71b9fc" })
hi(0, "NeoTreeDirectoryName", { fg = "#71b9fc" })
hi(0, "NeoTreeDotfile", { fg = "#626262" })
hi(0, "NeoTreeExpander", { fg = "#6e69a2" })
hi(0, "NeoTreeFadeText1", { fg = "#626262" })
hi(0, "NeoTreeFadeText2", { fg = "#444444" })
hi(0, "NeoTreeFileNameOpened", { fg = "#ffb9e2" })
hi(0, "NeoTreeFilterTerm", { bold = true, fg = "#a5e76e" })
hi(0, "NeoTreeFloatTitle", { fg = "#a8a9d9" })
hi(0, "NeoTreeGitAdded", { fg = "#a5e76e" })
hi(0, "NeoTreeGitConflict", { fg = "#ff7e93" })
hi(0, "NeoTreeGitDeleted", { fg = "#ff7e93" })
hi(0, "NeoTreeGitIgnored", { fg = "#6e69a2" })
hi(0, "NeoTreeGitModified", { fg = "#fbe29f" })
hi(0, "NeoTreeGitStaged", { fg = "#a5e76e" })
hi(0, "NeoTreeGitUnstaged", { fg = "#ff7e93" })
hi(0, "NeoTreeGitUntracked", { fg = "#71b9fc" })
hi(0, "NeoTreeIndentMarker", { fg = "#6e69a2" })
hi(0, "NeoTreeMessage", { fg = "#505050", italic = true })
hi(0, "NeoTreeModified", { fg = "#e9d25c" })
hi(0, "NeoTreeNormal", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#71b9fc" })
hi(0, "NeoTreeStatusLineNC", { bg = "#171a1f", fg = "#1b142e" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#ffb9e2" })
hi(0, "NeoTreeTabActive", { bg = "#171a1f", bold = true, fg = "#bdb9fc" })
hi(0, "NeoTreeTabInactive", { bg = "#1d2027", fg = "#6e69a2" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#171a1f", fg = "#1b142e" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#1d2027", fg = "#221939" })
hi(0, "NeoTreeTitleBar", { bg = "#9ab0f2", fg = "#1b142e" })
hi(0, "NeoTreeVertSplit", { bg = "#1d2027", fg = "#221939" })
hi(0, "NoiceCmdline", { fg = "#d1d4fc" })
hi(0, "NoiceCmdlineIcon", { fg = "#65e2ea", italic = true })
hi(0, "NoiceCmdlineIconCalculator", { fg = "#65e2ea", italic = true })
hi(0, "NoiceCmdlineIconCmdline", { fg = "#65e2ea", italic = true })
hi(0, "NoiceCmdlineIconFilter", { fg = "#65e2ea", italic = true })
hi(0, "NoiceCmdlineIconHelp", { fg = "#65e2ea", italic = true })
hi(0, "NoiceCmdlineIconIncRename", { fg = "#65e2ea", italic = true })
hi(0, "NoiceCmdlineIconInput", { fg = "#65e2ea", italic = true })
hi(0, "NoiceCmdlineIconLua", { fg = "#65e2ea", italic = true })
hi(0, "NoiceCmdlineIconSearch", { fg = "#fbe29f" })
hi(0, "NoiceCmdlinePopup", { bg = "#1d2027", fg = "#d1d4fc" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#bdb9fc" })
hi(0, "NoiceCmdlinePopupBorderCalculator", { fg = "#bdb9fc" })
hi(0, "NoiceCmdlinePopupBorderCmdline", { fg = "#bdb9fc" })
hi(0, "NoiceCmdlinePopupBorderFilter", { fg = "#bdb9fc" })
hi(0, "NoiceCmdlinePopupBorderHelp", { fg = "#bdb9fc" })
hi(0, "NoiceCmdlinePopupBorderIncRename", { fg = "#bdb9fc" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#bdb9fc" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#bdb9fc" })
hi(0, "NoiceCmdlinePopupBorderSearch", { fg = "#fbe29f" })
hi(0, "NoiceCmdlinePrompt", { bold = true, fg = "#71b9fc" })
hi(0, "NoiceCompletionItemKindClass", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindColor", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindConstant", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindConstructor", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindEnum", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindEnumMember", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindField", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindFile", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindFolder", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindFunction", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindInterface", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindKeyword", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindMethod", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindModule", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindProperty", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindSnippet", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindStruct", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindText", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindUnit", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindValue", { fg = "#ffb9e2" })
hi(0, "NoiceCompletionItemKindVariable", { fg = "#ffb9e2" })
hi(0, "NoiceConfirm", { bg = "#1d2027", fg = "#d1d4fc" })
hi(0, "NoiceConfirmBorder", { fg = "#71b9fc" })
hi(0, "NoiceCursor", { bg = "#ced6ef", fg = "#221939" })
hi(0, "NoiceFormatConfirm", { bg = "#2a2c33" })
hi(0, "NoiceFormatConfirmDefault", { bg = "#47484d", bold = true })
hi(0, "NoiceFormatDate", { fg = "#ffb9e2" })
hi(0, "NoiceFormatEvent", { fg = "#6e69a2" })
hi(0, "NoiceFormatKind", { fg = "#6e69a2" })
hi(0, "NoiceFormatLevelDebug", { fg = "#6e69a2" })
hi(0, "NoiceFormatLevelError", { bg = "#292c37", fg = "#ff7e93", italic = true })
hi(0, "NoiceFormatLevelInfo", { bg = "#2d3037", fg = "#65e2ea", italic = true })
hi(0, "NoiceFormatLevelOff", { fg = "#6e69a2" })
hi(0, "NoiceFormatLevelTrace", { fg = "#6e69a2" })
hi(0, "NoiceFormatLevelWarn", { bg = "#323232", fg = "#fbe29f", italic = true })
hi(0, "NoiceFormatProgressDone", { bg = "#4d5364", fg = "#d1d4fc" })
hi(0, "NoiceFormatProgressTodo", { bg = "#2a2c33" })
hi(0, "NoiceFormatTitle", { bold = true, fg = "#71b9fc" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NoiceLspProgressClient", { bold = true, fg = "#71b9fc" })
hi(0, "NoiceLspProgressSpinner", { fg = "#f9b36f" })
hi(0, "NoiceLspProgressTitle", { fg = "#6e69a2" })
hi(0, "NoiceMini", { fg = "#d1d4fc" })
hi(0, "NoicePopup", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "NoicePopupBorder", { fg = "#71b9fc" })
hi(0, "NoicePopupmenu", { bg = "#2a2d34", fg = "#9494c6" })
hi(0, "NoicePopupmenuBorder", { fg = "#71b9fc" })
hi(0, "NoicePopupmenuMatch", { fg = "#ffb9e2" })
hi(0, "NoicePopupmenuSelected", { bg = "#47484d", bold = true, fg = "#d1d4fc" })
hi(0, "NoiceScrollbar", { bg = "#47484d" })
hi(0, "NoiceScrollbarThumb", { bg = "#6f7177" })
hi(0, "NoiceSplit", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "NoiceSplitBorder", { fg = "#71b9fc" })
hi(0, "NoiceVirtualText", { bg = "#2d3037", fg = "#65e2ea", italic = true })
hi(0, "NonText", { fg = "#6e69a2" })
hi(0, "Normal", { bg = "#1d2027", fg = "#d1d4fc" })
hi(0, "NormalFloat", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "NormalNC", { bg = "#181b20", fg = "#d1d4fc" })
hi(0, "NormalSB", { bg = "#111216", fg = "#d1d4fc" })
hi(0, "NotifyDEBUGBorder", { fg = "#f9b36f" })
hi(0, "NotifyDEBUGIcon", { fg = "#f9b36f" })
hi(0, "NotifyDEBUGTitle", { fg = "#f9b36f", italic = true })
hi(0, "NotifyERRORBorder", { fg = "#ff7e93" })
hi(0, "NotifyERRORIcon", { fg = "#ff7e93" })
hi(0, "NotifyERRORTitle", { fg = "#ff7e93", italic = true })
hi(0, "NotifyINFOBorder", { fg = "#71b9fc" })
hi(0, "NotifyINFOIcon", { fg = "#71b9fc" })
hi(0, "NotifyINFOTitle", { fg = "#71b9fc", italic = true })
hi(0, "NotifyTRACEBorder", { fg = "#fbdfd5" })
hi(0, "NotifyTRACEIcon", { fg = "#fbdfd5" })
hi(0, "NotifyTRACETitle", { fg = "#fbdfd5", italic = true })
hi(0, "NotifyWARNBorder", { fg = "#fbe29f" })
hi(0, "NotifyWARNIcon", { fg = "#fbe29f" })
hi(0, "NotifyWARNTitle", { fg = "#fbe29f", italic = true })
hi(0, "Number", { fg = "#f9b36f" })
hi(0, "NvimInternalError", { bg = "#c149de", ctermbg = 9, ctermfg = 9, fg = "#e74d00" })
hi(0, "NvimSeparator", { bg = "#1d2027", fg = "#a86ed3" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#71b9fc" })
hi(0, "NvimTreeFolderIcon", { fg = "#71b9fc" })
hi(0, "NvimTreeFolderName", { fg = "#71b9fc" })
hi(0, "NvimTreeGitDeleted", { fg = "#ff7e93" })
hi(0, "NvimTreeGitDirty", { fg = "#fbe29f" })
hi(0, "NvimTreeGitNew", { fg = "#71b9fc" })
hi(0, "NvimTreeImageFile", { fg = "#d1d4fc" })
hi(0, "NvimTreeIndentMarker", { fg = "#6e69a2" })
hi(0, "NvimTreeNormal", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "NvimTreeOpenedFile", { fg = "#ffb9e2" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#71b9fc" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#bdb9fc" })
hi(0, "NvimTreeSpecialFile", { fg = "#fccac2" })
hi(0, "NvimTreeStatuslineNc", { bg = "#171a1f", fg = "#1b142e" })
hi(0, "NvimTreeSymlink", { fg = "#ffb9e2" })
hi(0, "NvimTreeWinSeparator", { bg = "#1d2027", fg = "#221939" })
hi(0, "Operator", { fg = "#65e2ea" })
hi(0, "Pmenu", { bg = "#2a2d34", fg = "#9494c6" })
hi(0, "PmenuSbar", { bg = "#47484d" })
hi(0, "PmenuSel", { bg = "#47484d", bold = true, fg = "#d1d4fc" })
hi(0, "PmenuThumb", { bg = "#6f7177" })
hi(0, "PreProc", { fg = "#ffb9e2" })
hi(0, "Question", { fg = "#71b9fc" })
hi(0, "QuickFixLine", { bg = "#47484d", bold = true })
hi(0, "RedrawDebugClear", { bg = "#d0fff5", ctermbg = 11 })
hi(0, "RedrawDebugComposed", { bg = "#007687", ctermbg = 10 })
hi(0, "RedrawDebugRecompose", { bg = "#c149de", ctermbg = 9 })
hi(0, "Repeat", { fg = "#dc9cf4" })
hi(0, "ScrollView", { bg = "#47484d", bold = true })
hi(0, "Search", { bg = "#4d5364", fg = "#d1d4fc" })
hi(0, "SearchSV", { fg = "#2b5a6d" })
hi(0, "SignColumn", { fg = "#494071" })
hi(0, "SignColumnSB", { bg = "#111216", fg = "#494071" })
hi(0, "Special", { fg = "#ffb9e2" })
hi(0, "SpecialKey", { fg = "#d1d4fc" })
hi(0, "SpellBad", { sp = "#f38ba8", undercurl = true })
hi(0, "SpellCap", { sp = "#f9e2af", undercurl = true })
hi(0, "SpellLocal", { sp = "#89b4fa", undercurl = true })
hi(0, "SpellRare", { sp = "#a6e3a1", undercurl = true })
hi(0, "Statement", { fg = "#dc9cf4" })
hi(0, "StatusLine", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "StatusLineNC", { bg = "#171a1f", fg = "#494071" })
hi(0, "StorageClass", { fg = "#fbe29f" })
hi(0, "String", { fg = "#a5e76e" })
hi(0, "Structure", { fg = "#fbe29f" })
hi(0, "Substitute", { bg = "#47484d", fg = "#ffb9e2" })
hi(0, "TSRainbowBlue", { fg = "#71b9fc" })
hi(0, "TSRainbowCyan", { fg = "#7de8c9" })
hi(0, "TSRainbowGreen", { fg = "#a5e76e" })
hi(0, "TSRainbowOrange", { fg = "#f9b36f" })
hi(0, "TSRainbowRed", { fg = "#ff7e93" })
hi(0, "TSRainbowViolet", { fg = "#dc9cf4" })
hi(0, "TSRainbowYellow", { fg = "#fbe29f" })
hi(0, "TabLine", { bg = "#171a1f", fg = "#494071" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#47484d", fg = "#a5e76e" })
hi(0, "TelescopeBorder", { link = "FloatBorder" })
hi(0, "TelescopeMatching", { fg = "#71b9fc" })
hi(0, "TelescopeMultiIcon", { fg = "#fccac2" })
hi(0, "TelescopeMultiSelection", { fg = "#fbe29f" })
hi(0, "TelescopeNormal", { bg = "#1d2027", fg = "#d1d4fc" })
hi(0, "TelescopePreviewBlock", { fg = "#f9b36f" })
hi(0, "TelescopePreviewBorder", { fg = "#71b9fc" })
hi(0, "TelescopePreviewCharDev", { fg = "#f9b36f" })
hi(0, "TelescopePreviewDate", { fg = "#71b9fc" })
hi(0, "TelescopePreviewDirectory", { fg = "#71b9fc" })
hi(0, "TelescopePreviewExecute", { fg = "#a5e76e" })
hi(0, "TelescopePreviewGroup", { fg = "#f9b36f" })
hi(0, "TelescopePreviewHyphen", { fg = "#6e69a2" })
hi(0, "TelescopePreviewLine", { bg = "#47484d", bold = true })
hi(0, "TelescopePreviewLink", { fg = "#ffb9e2" })
hi(0, "TelescopePreviewMatch", { bg = "#4d5364", fg = "#d1d4fc" })
hi(0, "TelescopePreviewMessage", { bg = "#1d2027", fg = "#d1d4fc" })
hi(0, "TelescopePreviewMessageFillchar", { bg = "#1d2027", fg = "#d1d4fc" })
hi(0, "TelescopePreviewNormal", { bg = "#1d2027", fg = "#d1d4fc" })
hi(0, "TelescopePreviewPipe", { fg = "#f9b36f" })
hi(0, "TelescopePreviewRead", { fg = "#f9b36f" })
hi(0, "TelescopePreviewSize", { fg = "#a5e76e" })
hi(0, "TelescopePreviewSocket", { fg = "#dc9cf4" })
hi(0, "TelescopePreviewSticky", { fg = "#dc9cf4" })
hi(0, "TelescopePreviewTitle", { fg = "#71b9fc" })
hi(0, "TelescopePreviewUser", { fg = "#f9b36f" })
hi(0, "TelescopePreviewWrite", { fg = "#dc9cf4" })
hi(0, "TelescopePromptBorder", { fg = "#71b9fc" })
hi(0, "TelescopePromptCounter", { fg = "#6e69a2" })
hi(0, "TelescopePromptNormal", { bg = "#1d2027", fg = "#d1d4fc" })
hi(0, "TelescopePromptPrefix", { fg = "#fccac2" })
hi(0, "TelescopePromptTitle", { fg = "#71b9fc" })
hi(0, "TelescopeResultsBorder", { fg = "#71b9fc" })
hi(0, "TelescopeResultsClass", { fg = "#71b9fc" })
hi(0, "TelescopeResultsComment", { fg = "#6e69a2", italic = true })
hi(0, "TelescopeResultsConstant", { fg = "#f9b36f" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#3d3f43" })
hi(0, "TelescopeResultsDiffChange", { bg = "#272a33" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#343946" })
hi(0, "TelescopeResultsDiffUntracked", { fg = "#6e69a2" })
hi(0, "TelescopeResultsField", { fg = "#71b9fc" })
hi(0, "TelescopeResultsFunction", { fg = "#71b9fc" })
hi(0, "TelescopeResultsIdentifier", { fg = "#fccac2" })
hi(0, "TelescopeResultsLineNr", { fg = "#494071" })
hi(0, "TelescopeResultsMethod", {})
hi(0, "TelescopeResultsNormal", { bg = "#1d2027", fg = "#d1d4fc" })
hi(0, "TelescopeResultsNumber", { fg = "#f9b36f" })
hi(0, "TelescopeResultsOperator", { fg = "#65e2ea" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#ffb9e2" })
hi(0, "TelescopeResultsStruct", {})
hi(0, "TelescopeResultsTitle", { fg = "#71b9fc" })
hi(0, "TelescopeResultsVariable", { fg = "#ffb9e2" })
hi(0, "TelescopeSelection", { bg = "#31343a", bold = true, fg = "#d1d4fc" })
hi(0, "TelescopeSelectionCaret", { fg = "#fccac2" })
hi(0, "TelescopeTitle", { fg = "#71b9fc" })
hi(0, "Title", { bold = true, fg = "#71b9fc" })
hi(0, "Todo", { bg = "#ffd5d7", bold = true, fg = "#221939" })
hi(0, "TreesitterContext", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "TreesitterContextBottom", {})
hi(0, "TreesitterContextLineNumber", { fg = "#494071" })
hi(0, "Type", { fg = "#fbe29f" })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", { fg = "#47ceef" })
hi(0, "Visual", { bg = "#47484d", bold = true })
hi(0, "VisualNOS", { bg = "#47484d", bold = true })
hi(0, "WarningMsg", { fg = "#fbe29f" })
hi(0, "WhichKey", { link = "NormalFloat" })
hi(0, "WhichKeyBorder", { link = "FloatBorder" })
hi(0, "WhichKeyDesc", { fg = "#ffb9e2" })
hi(0, "WhichKeyFloat", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "WhichKeyGroup", { fg = "#71b9fc" })
hi(0, "WhichKeySeparator", { fg = "#6e69a2", italic = true })
hi(0, "WhichKeySeperator", { fg = "#6e69a2" })
hi(0, "WhichKeyValue", { fg = "#6e69a2" })
hi(0, "Whitespace", { fg = "#494071" })
hi(0, "WildMenu", { bg = "#6f7177" })
hi(0, "WinBar", { fg = "#fbdfd5" })
hi(0, "barbecue_basename", { bold = true, fg = "#d1d4fc" })
hi(0, "barbecue_context", { fg = "#d1d4fc" })
hi(0, "barbecue_context_array", { fg = "#71b9fc" })
hi(0, "barbecue_context_boolean", { fg = "#f9b36f" })
hi(0, "barbecue_context_class", { fg = "#fbe29f" })
hi(0, "barbecue_context_constant", { fg = "#f9b36f" })
hi(0, "barbecue_context_constructor", { fg = "#71b9fc" })
hi(0, "barbecue_context_enum", { fg = "#a5e76e" })
hi(0, "barbecue_context_enum_member", { fg = "#ff7e93" })
hi(0, "barbecue_context_event", { fg = "#71b9fc" })
hi(0, "barbecue_context_field", { fg = "#a5e76e" })
hi(0, "barbecue_context_file", { fg = "#71b9fc" })
hi(0, "barbecue_context_function", { fg = "#71b9fc" })
hi(0, "barbecue_context_interface", { fg = "#fbe29f" })
hi(0, "barbecue_context_key", { fg = "#fccac2" })
hi(0, "barbecue_context_method", { fg = "#71b9fc" })
hi(0, "barbecue_context_module", { fg = "#71b9fc" })
hi(0, "barbecue_context_namespace", { fg = "#71b9fc" })
hi(0, "barbecue_context_null", { fg = "#f9b36f" })
hi(0, "barbecue_context_number", { fg = "#f9b36f" })
hi(0, "barbecue_context_object", { fg = "#71b9fc" })
hi(0, "barbecue_context_operator", { fg = "#71b9fc" })
hi(0, "barbecue_context_package", { fg = "#71b9fc" })
hi(0, "barbecue_context_property", { fg = "#a5e76e" })
hi(0, "barbecue_context_string", { fg = "#a5e76e" })
hi(0, "barbecue_context_struct", { fg = "#71b9fc" })
hi(0, "barbecue_context_type_parameter", { fg = "#71b9fc" })
hi(0, "barbecue_context_variable", { fg = "#fccac2" })
hi(0, "barbecue_dirname", { fg = "#817eb4" })
hi(0, "barbecue_ellipsis", { fg = "#817eb4" })
hi(0, "barbecue_modified", { fg = "#f9b36f" })
hi(0, "barbecue_normal", { fg = "#d1d4fc" })
hi(0, "barbecue_separator", { fg = "#817eb4" })
hi(0, "debugBreakpoint", { bg = "#1d2027", fg = "#6e69a2" })
hi(0, "debugPC", { bg = "#111216" })
hi(0, "diffAdded", { fg = "#a5e76e" })
hi(0, "diffChanged", { fg = "#71b9fc" })
hi(0, "diffFile", { fg = "#71b9fc" })
hi(0, "diffIndexLine", { fg = "#7de8c9" })
hi(0, "diffLine", { fg = "#6e69a2" })
hi(0, "diffNewFile", { fg = "#f9b36f" })
hi(0, "diffOldFile", { fg = "#fbe29f" })
hi(0, "diffRemoved", { fg = "#ff7e93" })
hi(0, "healthError", { fg = "#ff7e93" })
hi(0, "healthSuccess", { fg = "#7de8c9" })
hi(0, "healthWarning", { fg = "#fbe29f" })
hi(0, "htmlH1", { bold = true, fg = "#ffb9e2" })
hi(0, "htmlH2", { bold = true, fg = "#71b9fc" })
hi(0, "illuminatedCurWord", { bg = "#47484d" })
hi(0, "illuminatedWord", { bg = "#47484d" })
hi(0, "lCursor", { bg = "#ced6ef", fg = "#221939" })
hi(0, "lualine_a_24_command", { bg = "#efafd4", fg = "#221939" })
hi(0, "lualine_a_24_inactive", { bg = "#171a1f", fg = "#71b9fc" })
hi(0, "lualine_a_24_insert", { bg = "#90deef", fg = "#221939" })
hi(0, "lualine_a_24_normal", { bg = "#9ab0f2", fg = "#1b142e" })
hi(0, "lualine_a_24_replace", { bg = "#b2a2f1", fg = "#221939" })
hi(0, "lualine_a_24_terminal", { bg = "#90deef", fg = "#221939" })
hi(0, "lualine_a_24_visual", { bg = "#a0b7fd", fg = "#221939" })
hi(0, "lualine_a_command", { bg = "#efafd4", bold = true, fg = "#221939" })
hi(0, "lualine_a_inactive", { bg = "#171a1f", fg = "#71b9fc" })
hi(0, "lualine_a_insert", { bg = "#90deef", bold = true, fg = "#221939" })
hi(0, "lualine_a_normal", { bg = "#9ab0f2", bold = true, fg = "#1b142e" })
hi(0, "lualine_a_replace", { bg = "#b2a2f1", bold = true, fg = "#221939" })
hi(0, "lualine_a_terminal", { bg = "#90deef", bold = true, fg = "#221939" })
hi(0, "lualine_a_visual", { bg = "#a0b7fd", bold = true, fg = "#221939" })
hi(0, "lualine_b_command", { bg = "#47484d", fg = "#f9b36f" })
hi(0, "lualine_b_inactive", { bg = "#171a1f", bold = true, fg = "#494071" })
hi(0, "lualine_b_insert", { bg = "#47484d", fg = "#7de8c9" })
hi(0, "lualine_b_normal", { bg = "#47484d", fg = "#71b9fc" })
hi(0, "lualine_b_replace", { bg = "#47484d", fg = "#ff7e93" })
hi(0, "lualine_b_terminal", { bg = "#47484d", fg = "#7de8c9" })
hi(0, "lualine_b_visual", { bg = "#47484d", fg = "#dc9cf4" })
hi(0, "lualine_c_diagnostics_error_command", { bg = "#171a1f", fg = "#ff7e93" })
hi(0, "lualine_c_diagnostics_error_inactive", { bg = "#171a1f", fg = "#ff7e93" })
hi(0, "lualine_c_diagnostics_error_insert", { bg = "#171a1f", fg = "#ff7e93" })
hi(0, "lualine_c_diagnostics_error_normal", { bg = "#171a1f", fg = "#ff7e93" })
hi(0, "lualine_c_diagnostics_error_replace", { bg = "#171a1f", fg = "#ff7e93" })
hi(0, "lualine_c_diagnostics_error_terminal", { bg = "#171a1f", fg = "#ff7e93" })
hi(0, "lualine_c_diagnostics_error_visual", { bg = "#171a1f", fg = "#ff7e93" })
hi(0, "lualine_c_diagnostics_hint_command", { bg = "#171a1f", fg = "#7de8c9" })
hi(0, "lualine_c_diagnostics_hint_inactive", { bg = "#171a1f", fg = "#7de8c9" })
hi(0, "lualine_c_diagnostics_hint_insert", { bg = "#171a1f", fg = "#7de8c9" })
hi(0, "lualine_c_diagnostics_hint_normal", { bg = "#171a1f", fg = "#7de8c9" })
hi(0, "lualine_c_diagnostics_hint_replace", { bg = "#171a1f", fg = "#7de8c9" })
hi(0, "lualine_c_diagnostics_hint_terminal", { bg = "#171a1f", fg = "#7de8c9" })
hi(0, "lualine_c_diagnostics_hint_visual", { bg = "#171a1f", fg = "#7de8c9" })
hi(0, "lualine_c_diagnostics_info_command", { bg = "#171a1f", fg = "#65e2ea" })
hi(0, "lualine_c_diagnostics_info_inactive", { bg = "#171a1f", fg = "#65e2ea" })
hi(0, "lualine_c_diagnostics_info_insert", { bg = "#171a1f", fg = "#65e2ea" })
hi(0, "lualine_c_diagnostics_info_normal", { bg = "#171a1f", fg = "#65e2ea" })
hi(0, "lualine_c_diagnostics_info_replace", { bg = "#171a1f", fg = "#65e2ea" })
hi(0, "lualine_c_diagnostics_info_terminal", { bg = "#171a1f", fg = "#65e2ea" })
hi(0, "lualine_c_diagnostics_info_visual", { bg = "#171a1f", fg = "#65e2ea" })
hi(0, "lualine_c_diagnostics_warn_command", { bg = "#171a1f", fg = "#fbe29f" })
hi(0, "lualine_c_diagnostics_warn_inactive", { bg = "#171a1f", fg = "#fbe29f" })
hi(0, "lualine_c_diagnostics_warn_insert", { bg = "#171a1f", fg = "#fbe29f" })
hi(0, "lualine_c_diagnostics_warn_normal", { bg = "#171a1f", fg = "#fbe29f" })
hi(0, "lualine_c_diagnostics_warn_replace", { bg = "#171a1f", fg = "#fbe29f" })
hi(0, "lualine_c_diagnostics_warn_terminal", { bg = "#171a1f", fg = "#fbe29f" })
hi(0, "lualine_c_diagnostics_warn_visual", { bg = "#171a1f", fg = "#fbe29f" })
hi(0, "lualine_c_filetype_DevIconDefault_command", { bg = "#171a1f", fg = "#5c848b" })
hi(0, "lualine_c_filetype_DevIconDefault_inactive", { bg = "#171a1f", fg = "#5c848b" })
hi(0, "lualine_c_filetype_DevIconDefault_insert", { bg = "#171a1f", fg = "#5c848b" })
hi(0, "lualine_c_filetype_DevIconDefault_normal", { bg = "#171a1f", fg = "#5c848b" })
hi(0, "lualine_c_filetype_DevIconDefault_replace", { bg = "#171a1f", fg = "#5c848b" })
hi(0, "lualine_c_filetype_DevIconDefault_terminal", { bg = "#171a1f", fg = "#5c848b" })
hi(0, "lualine_c_filetype_DevIconDefault_visual", { bg = "#171a1f", fg = "#5c848b" })
hi(0, "lualine_c_inactive", { bg = "#171a1f", fg = "#6e69a2" })
hi(0, "lualine_c_normal", { bg = "#171a1f", fg = "#d1d4fc" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#47484d", fg = "#f9b36f" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_c_normal", { bg = "#171a1f", fg = "#f9b36f" })
hi(0, "lualine_transitional_lualine_a_insert_to_lualine_b_insert", { bg = "#47484d", fg = "#a5e76e" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#47484d", fg = "#71b9fc" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_c_normal", { bg = "#171a1f", fg = "#71b9fc" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_filetype_DevIconDefault_command", { bg = "#171a1f", fg = "#494071" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_normal", { bg = "#171a1f", fg = "#494071" })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_c_filetype_DevIconDefault_insert", { bg = "#171a1f", fg = "#494071" })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_c_normal", { bg = "#171a1f", fg = "#494071" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconDefault_normal", { bg = "#171a1f", fg = "#494071" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#171a1f", fg = "#494071" })
hi(0, "lualine_x_diff_added", { link = "DiffAdd" })
hi(0, "lualine_x_diff_modified", { link = "DiffChange" })
hi(0, "lualine_x_diff_removed", { link = "DiffDelete" })
hi(0, "markdownCode", { fg = "#fccac2" })
hi(0, "markdownCodeBlock", { fg = "#fccac2" })
hi(0, "markdownH1", { fg = "#bdb9fc" })
hi(0, "markdownH2", { fg = "#dc9cf4" })
hi(0, "markdownH3", { fg = "#a5e76e" })
hi(0, "markdownH4", { fg = "#fbe29f" })
hi(0, "markdownH5", { fg = "#ffb9e2" })
hi(0, "markdownH6", { fg = "#7de8c9" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#f9b36f" })
hi(0, "markdownLinkText", { fg = "#71b9fc", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#1d2027", fg = "#d1d4fc" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#fccac2" })
hi(0, "mkdCodeStart", { bold = true, fg = "#fccac2" })
hi(0, "qfFileName", { fg = "#71b9fc" })
hi(0, "qfLineNr", { fg = "#fbe29f" })
hi(0, "rainbowcol1", { fg = "#ff7e93" })
hi(0, "rainbowcol2", { fg = "#7de8c9" })
hi(0, "rainbowcol3", { fg = "#fbe29f" })
hi(0, "rainbowcol4", { fg = "#71b9fc" })
hi(0, "rainbowcol5", { fg = "#ffb9e2" })
hi(0, "rainbowcol6", { fg = "#fccac2" })
hi(0, "rainbowcol7", { fg = "#a5e76e" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#6c7086"
g.terminal_color_1 = "#f38ba8"
g.terminal_color_2 = "#a6e3a1"
g.terminal_color_3 = "#f9e2af"
g.terminal_color_4 = "#89b4fa"
g.terminal_color_5 = "#f5c2e7"
g.terminal_color_6 = "#89dceb"
g.terminal_color_7 = "#cdd6f4"
g.terminal_color_8 = "#7f849c"
g.terminal_color_9 = "#f38ba8"
g.terminal_color_10 = "#a6e3a1"
g.terminal_color_11 = "#f9e2af"
g.terminal_color_12 = "#89b4fa"
g.terminal_color_13 = "#f5c2e7"
g.terminal_color_14 = "#89dceb"
g.terminal_color_15 = "#cdd6f4"
